try:
    result = 10/0
    print(result)
except:
    print("An exception occured")
    # raise
    